name: Main
on: 
  push: 
    branches:
    - main
    - production
  pull_request:
    branches:
    - main
    - production
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r

      # - name: Upload artifact for deployment jobs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: python-app
      #     path: |
      #       release.zip
      #       !venv/
  deploy:
    needs: build
    name: Wdrożenia na serwer
    runs-on: ubuntu-latest
    steps:
    - name: Github Checkout
      uses: actions/checkout@v4

    - name: Synchronizacja do Azure App Service
      uses: azure/webapps-deploy@v1
      with: 
        app-name: archapp12
        publish-profile: ${{ secrets.AZURE_WEB_APP }}
    
      # uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      # with:
      #   server: 172.206.249.203
      #   username: ${{ secrets.ftp_username }}
      #   password: ${{ secrets.ftp_password }}
      #   server-dir: app_1/
    
  
    
